config/routes.rb
Rails.application.routes.draw do

  # Semi-static page routes
  get 'home', to: 'home#index', as: :home
  get 'home/about', to: 'home#about', as: :about
  get 'home/contact', to: 'home#contact', as: :contact
  get 'home/privacy', to: 'home#privacy', as: :privacy
  get 'home/search', to: 'home#search', as: :search

  # Resource routes (maps HTTP verbs to controller actions automatically):
  resources :employees
  resources :stores
  resources :assignments

  # Custom routes
  patch 'assignments/:id/terminate', to: 'assignments#terminate', as: :terminate_assignment

  # You can have the root of your site routed with 'root'
  root 'home#index'
end

app/models/employee.rb
class Employee < ApplicationRecord
  include AppHelpers::Validations
  include AppHelpers::Deletions
  include AppHelpers::Activeable::InstanceMethods
  extend AppHelpers::Activeable::ClassMethods
  
  has_secure_password

  # Relationships
  has_many :assignments 
  has_many :stores, through: :assignments
  has_many :shifts, through: :assignments 
  has_many :pay_grades, through: :assignments
  has_many :pay_grade_rates, through: :pay_grades

  # Scopes
  scope :younger_than_18, -> { where('date_of_birth > ?', 18.years.ago.to_date) }
  scope :is_18_or_older,  -> { where('date_of_birth <= ?', 18.years.ago.to_date) }
  scope :regulars,        -> { where('role = ?', 'employee') }
  scope :managers,        -> { where('role = ?', 'manager') }
  scope :admins,          -> { where('role = ?', 'admin') }
  scope :alphabetical,    -> { order('last_name, first_name') }

  # Validations
  validates_presence_of :first_name, :last_name, :ssn
  validates_date :date_of_birth, :on_or_before => lambda { 14.years.ago }, on_or_before_message: 'must be at least 14 years old'
  validates_format_of :phone, with: /\A(\d{10}|\(?\d{3}\)?[-. ]\d{3}[-.]\d{4})\z/, message: 'should be 10 digits (area code needed) and delimited with dashes only'
  validates_format_of :ssn, with: /\A\d{3}[- ]?\d{2}[- ]?\d{4}\z/, message: 'should be 9 digits and delimited with dashes only'
  validates_uniqueness_of :ssn
  validates_inclusion_of :role, in: %w[admin manager employee], message: 'is not an option'
  # ... more validations for phase 4 & 5
  validates :username, presence: true, uniqueness: { case_sensitive: false}
  validates_presence_of :role, on: :create
  validates_presence_of :password, on: :create 
  validates_presence_of :password_confirmation, on: :create 
  validates_confirmation_of :password, on: :create, message: 'does not match'
  validates_length_of :password, minimum: 4, message: 'must be at least 4 characters long', allow_blank: true

  # Other methods
  def name
    "#{last_name}, #{first_name}"
  end
  
  def proper_name
    "#{first_name} #{last_name}"
  end

  def over_18?
    date_of_birth.to_date < 18.years.ago.to_date
  end
  
  def age
    (Time.now.to_s(:number).to_i - date_of_birth.to_time.to_s(:number).to_i)/10e9.to_i
  end

  def current_assignment
    curr_assignment = self.assignments.current    
    return nil if curr_assignment.empty?
    curr_assignment.first   # return as a single object, not an array
  end

  # Add in methods for phases 4 & 5 for authentication and payment handling
  include EmployeePayment
  include EmployeeAuthentication

  # Callbacks
  before_save -> { strip_nondigits_from(:phone) }
  before_save -> { strip_nondigits_from(:ssn) }

  # ... additional callbacks in phases 4 & 5
  include EmployeeDeletion
  before_destroy -> { handle_deletion_request() }
  after_rollback -> { handle_deletion_failure() }

end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  def index
    # for phase 3 only
    @active_managers = Employee.managers.active.alphabetical.paginate(page: params[:page]).per_page(10)
    @active_employees = Employee.regulars.active.alphabetical.paginate(page: params[:page]).per_page(10)
    @inactive_employees = Employee.inactive.alphabetical.paginate(page: params[:page]).per_page(10)

  end

  def show
    retrieve_employee_assignments
  end

  def new
    @employee = Employee.new
  end

  def edit
  end

  def create
    @employee = Employee.new(employee_params)
    if @employee.save
      redirect_to @employee, notice: "Successfully added #{@employee.proper_name} as an employee."
    else
      render action: 'new'
    end
  end

  def update
    if @employee.update_attributes(employee_params)
      redirect_to @employee, notice: "Updated #{@employee.proper_name}'s information."
    else
      render action: 'edit'
    end
  end


  private
  # Use callbacks to share common setup or constraints between actions.
  def set_employee
    @employee = Employee.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def employee_params
    params.require(:employee).permit(:first_name, :last_name, :ssn, :phone, :date_of_birth, :role, :active)
  end

  def retrieve_employee_assignments
    @current_assignment = @employee.current_assignment
    @previous_assignments = @employee.assignments.to_a - [@current_assignment]
  end

end

app/helpers/employees_helper.rb
module EmployeesHelper
  def number_to_ssn(num)
    "#{num[0..2]}-#{num[3..4]}-#{num[5..8]}"
  end
end

app/views/employees/_active_employees.html.erb
<%= render partial: 'employee_lists', locals: {employees: @active_employees, state: 'active'} %>

app/views/employees/_active_lists.html.erb
<%= render partial: 'employee_lists', locals: {employees: @active_managers, role: 'managers', state: 'active'} %>
<p>&nbsp;</p>
<%= render partial: 'employee_lists', locals: {employees: @active_employees, state: 'active', role: 'employees'} %>

app/views/employees/_assignment_history.html.erb
<% unless @previous_assignments.empty? %>
  <div class="card">
    <div class="card-content">
      <h5>Previous Assignments</h5>

      <table class="striped highlight">
        <thead>
          <th>Store</th>
          <th>Dates</th>
        </thead>
        <% @previous_assignments.each do |assignment| %>
          <tr %>
            <td><%= link_to assignment.store.name, store_path(assignment.store) %></td>
            <td><%= assignment.start_date.strftime("%-m/%-d/%y") %> - <%= assignment.end_date.strftime("%-m/%-d/%y") %></td>
          </tr>
        <% end %>
      </table>
      <p class="supertiny"></p>
      <br />
    </div>
    <div class="card-action">
      <%= link_to "New Assignment", new_assignment_path(employee_id: @employee.id) %>
    </div>
  </div>
<% else %>
  <div class="card grey lighten-3">
    <div class="card-action">
      <%= link_to "New Assignment", new_assignment_path(employee_id: @employee.id) %>
    </div>
  </div>
<% end %>

app/views/employees/_employee_data.html.erb
<div class="card">
  <div class="card-content">
    <h4><%= @employee.proper_name %></h4>
    <h5><%= @employee.role.capitalize %></h5><br />

    <b>Current Assignment:&nbsp;&nbsp;</b><br>
      <% if @employee.current_assignment.nil? %>
        n/a<br /><br />
      <% else %>
        <%= link_to @employee.current_assignment.store.name, store_path(@employee.current_assignment.store) %><br />
        since <%= @employee.current_assignment.start_date.strftime("%b %-d, %Y") %><br /><br />

      <% end %>

    <b>Phone:&nbsp;&nbsp;</b><br>
      <%= number_to_phone @employee.phone %><br /><br />

    <b>Social Security Number:&nbsp;&nbsp;</b><br>
      <%= number_to_ssn @employee.ssn %><br /><br />

    <b>Date of Birth:&nbsp;&nbsp;</b><br>
      <%= @employee.date_of_birth.to_datetime.strftime("%b %-d, %Y") %><br /><br />


    <b>Active with AMC?&nbsp;&nbsp;</b>
      <%= @employee.active ? "Yes" : "No" %>
      <br>
  </div>
</div>

app/views/employees/_employee_lists.html.erb
<div class="card">
  <div class="card-content">
    <h4><%= state.capitalize %> <%= role.capitalize %> at AMC</h4>

    <% if employees.empty? %>
      <p>There are no <%= state.downcase %> <%= role.downcase %> at this time.</p>
    <% else %>

      <table class="striped highlight">
        <thead>
          <th>Name</th>
          <th>Current Assignment</th>
          <th>Phone</th>
          <th class="align_center">Options</th>
        </thead>
        <% for employee in employees %>
          <tr class="<%= cycle('dg_list_line_odd', 'dg_list_line_even') %>">
            <td><%= link_to employee.name, employee_path(employee) %></td>
            <td><%= employee.current_assignment.nil? ? 'n/a' : link_to(employee.current_assignment.store.name, store_path(employee.current_assignment.store))  %></td>
            <td><%= number_to_phone employee.phone %></td>

          <td class="align_center">
            <%= link_to edit_employee_path(employee) do %>
              <i class="material-icons">edit</i>
            <% end %>
          </td>
          </tr>
        <% end %>
      </table>
      <p class="supertiny"></p>
      <br />
      <%= will_paginate employees, previous_label: "Previous&nbsp;", next_label: "&nbsp;Next" %>
    <% end %>
  </div>
</div>

app/views/employees/_fields.html.erb
<%= f.input :first_name, label_html: { class: 'active' } %>
<%= f.input :last_name, label_html: { class: 'active' } %>
<%= f.input :date_of_birth, label_html: { class: 'active' } %>
<%= f.input :phone, label_html: { class: 'active' } %>
<%= f.input :role, collection: Employee::ROLES_LIST, include_blank: true %>
<%= f.input :active %>

app/views/employees/_inactive_employees.html.erb
<%= render partial: 'employee_lists', locals: {employees: @inactive_employees, state: 'inactive', role: 'employees'} %>

app/views/employees/edit.html.erb
<%= render partial: 'partials/form_structure', locals: {object: @employee, 
                                                        type_of_form: 'Employee',
                                                        fields: 'fields'} %>

app/views/employees/index.html.erb
<%= render partial: 'partials/index_structure', locals: {model_name: 'employee', 
                                                         primary: 'active_lists', 
                                                         secondary: 'inactive_employees',
                                                         sidebar: nil} %>

app/views/employees/new.html.erb
<%= render partial: 'partials/form_structure', locals: {object: @employee, 
                                                        type_of_form: 'New Employee',
                                                        fields: 'fields'} %>

app/views/employees/show.html.erb
<%= render partial: 'partials/show_structure', locals: {model_name: 'employee', 
                                                         object: @employee,
                                                         primary: 'employee_data', 
                                                         secondary: 'secondary_information',
                                                         sidebar: 'assignment_history'} %>