config/routes.rb
Rails.application.routes.draw do

  # Semi-static page routes
  get 'home', to: 'home#index', as: :home
  get 'home/about', to: 'home#about', as: :about
  get 'home/contact', to: 'home#contact', as: :contact
  get 'home/privacy', to: 'home#privacy', as: :privacy
  get 'home/search', to: 'home#search', as: :search

  # Resource routes (maps HTTP verbs to controller actions automatically):
  resources :employees
  resources :stores
  resources :assignments

  # Custom routes
  patch 'assignments/:id/terminate', to: 'assignments#terminate', as: :terminate_assignment

  # You can have the root of your site routed with 'root'
  root 'home#index'
end

app/models/assignment.rb
class Assignment < ApplicationRecord
  include AppHelpers::Validations
  include AppHelpers::Deletions

  # Relationships
  belongs_to :store
  belongs_to :employee
  belongs_to :pay_grade
  has_many :shifts 
  
  # Scopes
  scope :current,       -> { where('end_date IS NULL') }
  scope :past,          -> { where('end_date IS NOT NULL') }
  scope :by_store,      -> { joins(:store).order('name') }
  scope :by_employee,   -> { joins(:employee).order('last_name, first_name') }
  scope :chronological, -> { order(Arel.sql('start_date DESC, end_date IS NOT NULL, end_date DESC')) }
  scope :for_store,     ->(store) { where("store_id = ?", store.id) }
  scope :for_employee,  ->(employee) { where("employee_id = ?", employee.id) }
  scope :for_pay_grade, ->(pay_grade) { where("pay_grade_id = ?", pay_grade.id) }
  scope :for_role,      ->(role) { joins(:employee).where("role = ?", role) }
  scope :for_date,      ->(date) { where("start_date <= ? AND (end_date > ? OR end_date IS NULL)", date, date) }

  # Validations
  validates_presence_of :store_id, :employee_id, :pay_grade_id, :start_date
  validates_date :start_date, on_or_before: ->{ Date.current }, on_or_before_message: "cannot be in the future"
  validates_date :end_date, after: :start_date, on_or_before: ->{ Date.current }, allow_blank: true
  validate ->{ is_active_in_system(:employee) }
  validate ->{ is_active_in_system(:store) }
  validate ->{ is_active_in_system(:pay_grade) }  # phase 4 & 5 only

  # Other methods
  def terminate
    return false unless self.end_date.nil?
    self.start_date = Date.current
    end_previous_assignment
    remove_pending_shifts
    self.reload
  end

  # Callbacks
  before_create :end_previous_assignment

  # ... for phase 4 & 5 only
  before_destroy do
    verify_no_pending_shifts
    if errors.present?
      throw(:abort)
    else
      remove_pending_shifts
    end
  end

  private
  def end_previous_assignment
    current_assignment = Employee.find(self.employee_id).current_assignment
    if current_assignment.nil?
      return true 
    else
      current_assignment.update_attribute(:end_date, self.start_date.to_date)
    end
  end

  def verify_no_pending_shifts
    unless self.shifts.started.empty? && self.shifts.finished.empty?
      errors.add(:base, "This assignments is associated with worked shifts and cannot be deleted.")
    end
  end

  def remove_pending_shifts
    self.shifts.pending.each { |s| s.destroy }
  end
  
end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController
  before_action :set_assignment, only: [:show, :edit, :terminate, :destroy]

  def index
    # for phase 3 only
      @current_assignments = Assignment.current.chronological.paginate(page: params[:page]).per_page(10)
      @past_assignments = Assignment.past.chronological.paginate(page: params[:page]).per_page(10)
  end

  def new
    @assignment = Assignment.new
    @assignment.employee_id = params[:employee_id] unless params[:employee_id].nil?
  end

  def create
    @assignment = Assignment.new(assignment_params)
    if @assignment.save
      redirect_to assignments_path, notice: "Successfully added the assignment."
    else
      render action: 'new'
    end
  end

  def terminate
    if @assignment.terminate
      redirect_to assignments_path, notice: "Assignment for #{@assignment.employee.proper_name} terminated."
    end
  end

  def destroy
    @assignment.destroy
    redirect_to assignments_path, notice: "Removed assignment from the system."
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_assignment
    @assignment = Assignment.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def assignment_params
    params.require(:assignment).permit(:store_id, :employee_id, :start_date)
  end

end

app/helpers/assignments_helper.rb
module AssignmentsHelper
end

app/views/assignments/_assignments_list.html.erb
<div class="card">
  <div class="card-content">
    <h5><%= state.capitalize %> Assignments</h5>

    <% if assignments.empty? %>
      <p>There are no <%= state.downcase %> assignments at this time.</p>
    <% else %>

      <table class="striped highlight">
        <thead>
          <th>Employee Name</th>
          <th>Store Name</th>
          <th>Dates</th>
          <th>Options</th>
        </thead>
        <% assignments.each do |assignment| %>
          <tr %>
            <td><%= link_to assignment.employee.name, employee_path(assignment.employee) %></td>
            <td><%= link_to assignment.store.name, store_path(assignment.store) %></td>
            <td><%= assignment.start_date.strftime("%-m/%-d/%y") %> - <%= assignment.end_date.nil? ? 'Present' : assignment.end_date.strftime("%-m/%-d/%y") %></td>
            <td>
              <% if state.downcase == 'current' %>
                <%= link_to(terminate_assignment_path(assignment), method: :patch) do %>
                  <i class="material-icons">stop</i>
                <% end %>
              <% end %>
              &nbsp;&nbsp;&nbsp;&nbsp;
              <%= link_to(assignment_path(assignment), method: :delete, data: { confirm: 'Are you sure you wish to delete this assignment?' }) do %>
                  <i class="material-icons">delete</i>
              <% end %>
            </td>
          </tr>
        <% end %>
      </table>
      <p class="supertiny"></p>
      <br />
      <%= will_paginate assignments, previous_label: "Previous&nbsp;", next_label: "&nbsp;Next" %>
      <br />
    <% end %>
  </div>
</div>

app/views/assignments/_current_assignments.html.erb
<%= render partial: 'assignments_list', locals: { state: 'Current', 
                                                  assignments: @current_assignments } %>

app/views/assignments/_fields.html.erb
<%= f.input :employee_id, collection: Employee.alphabetical.active.to_a, include_blank: true %>
<%= f.input :store_id, collection: Store.alphabetical.active.to_a, include_blank: true %>
<%= f.input :start_date, label_html: { class: 'active' } %>

app/views/assignments/_past_assignments.html.erb
<%= render partial: 'assignments_list', locals: { state: 'Past', 
assignments: @past_assignments } %>

app/views/assignments/index.html.erb
<%= render partial: 'partials/index_structure', locals: {model_name: 'assignment', 
                                                         primary: 'current_assignments', 
                                                         secondary: 'past_assignments',
                                                         sidebar: nil} %>

app/views/assignments/new.html.erb
<%= render partial: 'partials/form_structure', locals: {object: @assignment, 
                                                        type_of_form: 'New Assignment',
                                                        fields: 'fields'} %>

app/views/assignments/show.html.erb
<h1>Assignments#show</h1>
<p>Find me in app/views/assignments/show.html.erb</p>