config/routes.rb
Rails.application.routes.draw do

  # Semi-static page routes
  get 'home', to: 'home#index', as: :home
  get 'home/about', to: 'home#about', as: :about
  get 'home/contact', to: 'home#contact', as: :contact
  get 'home/privacy', to: 'home#privacy', as: :privacy
  get 'home/search', to: 'home#search', as: :search

  # Resource routes (maps HTTP verbs to controller actions automatically):
  resources :employees
  resources :stores
  resources :assignments

  # Custom routes
  patch 'assignments/:id/terminate', to: 'assignments#terminate', as: :terminate_assignment

  # You can have the root of your site routed with 'root'
  root 'home#index'
end

app/models/store.rb
class Store < ApplicationRecord
  include AppHelpers::Validations
  include AppHelpers::Deletions
  include AppHelpers::Activeable::InstanceMethods
  extend AppHelpers::Activeable::ClassMethods

  # Relationships
  has_many :assignments
  has_many :employees, through: :assignments
  has_many :shifts, through: :assignments

  # Scopes
  scope :alphabetical, -> { order('name') }

  # Validations
  # make sure required fields are present
  validates_presence_of :name, :street, :city
  # if state is given, must be one of the choices given (no hacking this field)
  validates_inclusion_of :state, in:  %w[PA OH WV], message: "is not an option"
  # if zip included, it must be 5 digits only
  validates_format_of :zip, with: /\A\d{5}\z/, message: "should be five digits long"
  # phone can have dashes, spaces, dots and parens, but must be 10 digits
  validates_format_of :phone, with: /\A\(?\d{3}\)?[-. ]?\d{3}[-.]?\d{4}\z/, message: "should be 10 digits (area code needed) and delimited with dashes only"
  # make sure stores have unique names (case insensitive)
  validates_uniqueness_of :name, case_sensitive: false

  # Callbacks
  before_save    -> { strip_nondigits_from(:phone) }
  before_destroy -> { cannot_destroy_object() }
  
  # Misc Constants
  STATES_LIST = [['Ohio', 'OH'],['Pennsylvania', 'PA'],['West Virginia', 'WV']].freeze
  
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController

  before_action :set_store, only: [:show, :edit, :update, :destroy]


  def index
    # get data on all stores and paginate the output to 10 per page
    @active_stores = Store.active.alphabetical.paginate(page: params[:page]).per_page(10)
    @inactive_stores = Store.inactive.alphabetical.paginate(page: params[:ipage]).per_page(10)
  end

  def show
    @current_managers = @store.assignments.current.map{|a| a.employee}.sort_by{|e| e.name}.select{|e| e.role == 'manager'}
    @current_employees = @store.assignments.current.map{|a| a.employee}.sort_by{|e| e.name}
  end

  def new
    @store = Store.new
  end

  def edit
  end

  def create
    @store = Store.new(store_params)
    if @store.save
      redirect_to @store, notice: "Successfully added #{@store.name} to the system."
    else
      render action: 'new'
    end
  end

  def update
    if @store.update_attributes(store_params)
      redirect_to @store, notice: "Updated store information for #{@store.name}."
    else
      render action: 'edit'
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_store
    @store = Store.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def store_params
    params.require(:store).permit(:name, :street, :city, :phone, :state, :zip, :active)
  end

end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/_active_stores.html.erb
<%= render partial: 'store_lists', locals: {stores: @active_stores, state: 'active'} %>

app/views/stores/_employees_sidebar.html.erb
<div class="card">
  <div class="card-content">
    <h5>Current Employees</h5>

    <% if @current_employees.empty? %>
      <p>There are no employees assigned at this time.</p>
    <% else %>

      <table class="striped highlight">
        <% @current_employees.each do |employee| %>
          <tr %>
            <td><%= link_to employee.name, employee_path(employee) %></td>
          </tr>
        <% end %>
      </table>
      <p class="supertiny"></p>
      <br />
    <% end %>
  </div>
</div>

app/views/stores/_fields.html.erb
<%= f.input :name, label_html: { class: 'active' } %>
<%= f.input :street, label_html: { class: 'active' } %>
<%= f.input :city, label_html: { class: 'active' } %>
<%= f.input :phone, label_html: { class: 'active' } %>
<%= f.input :state, collection: Store::STATES_LIST, include_blank: true %>
<%= f.input :zip, label_html: { class: 'active' } %>
<%= f.input :active %>

app/views/stores/_inactive_stores.html.erb
<%= render partial: 'store_lists', locals: {stores: @inactive_stores, state: 'inactive'} %>

app/views/stores/_shifts_list.html.erb
<div class="card">
  <div class="card-content">
    <h5><%= state.capitalize %> Shifts</h5>

    <% if shifts.empty? %>
      <p>There are no <%= state.downcase %> shifts at this time.</p>
    <% else %>

      <table class="striped highlight">
        <thead>
          <th>Employee</th>
          <th>Date</th>
          <th>Starting</th>
        </thead>
        <% shifts.each do |shift| %>
          <tr %>
            <td><%= link_to shift.employee.name, employee_path(shift.employee) %></td>
            <td><%= shift.date.strftime("%-m/%-d") %></td>
            <td><%= shift.start_time.strftime("%l:%M %P") %></td>
          </tr>
        <% end %>
      </table>
      <p class="supertiny"></p>
      <br />
    <% end %>
  </div>
</div>

app/views/stores/_shifts_sidebar.html.erb
<%= render partial: 'shifts_list', locals: { state: 'Upcoming', 
                                             shifts: @upcoming_shifts } %>
<p>&nbsp;</p>

<%= render partial: 'shifts_list', locals: { state: 'Past', 
shifts: @past_shifts } %>

app/views/stores/_store_details.html.erb
<div class="card">
  <div class="card-content">
    <p>
      <h4>
        <%= @store.name %> Store
      </h4>
    </p>

    <p>
      <b>Address:</b><br>
      <%= @store.street %><br />
      <%= @store.city %>, <%= @store.state %> <%= @store.zip %>
    </p><br />

    <p>
      <b>Phone:</b><br>
      <%= number_to_phone @store.phone %>
    </p><br />

    <p>
      <b>Manager(s):</b><br>
      <%= 'n/a' if @current_managers.empty? %>
      <% @current_managers.each do |manager| %>
        <%= link_to manager.proper_name, employee_path(manager) %><br />
      <% end %>
    </p><br />

    <p>
      <b>Active:</b> 
      <%= @store.active ? "Yes" : "No" %>
    </p><br />
  </div>
</div>

app/views/stores/_store_lists.html.erb
<div class="card">
  <div class="card-content">
    <h4><%= state.capitalize %> Stores owned by AMC</h4>

    <% if stores.empty? %>
      <p>There are no <%= state.downcase %> stores at this time.</p>
    <% else %>

      <table class="striped highlight">
        <thead>
          <th>Name</th>
          <th>Current Assignments</th>
          <th>Phone</th>
          <th class="align_center">Options</th>
        </thead>
        <% stores.each do |store| %>
          <tr>
            <td><%= link_to store.name, store_path(store) %></td>
            <td><%= store.assignments.current.count %></td>
            <td><%= number_to_phone store.phone %></td>

            <td class="align_center">
              <%= link_to edit_store_path(store) do %>
                <i class="material-icons">edit</i>
              <% end %>
            </td>
          </tr>
        <% end %>
      </table>
      <p class="supertiny"></p>
      <br />
      <%= will_paginate stores, previous_label: "Previous&nbsp;", next_label: "&nbsp;Next" %>
    <% end %>
  </div>
</div>

app/views/stores/edit.html.erb
<%= render partial: 'partials/form_structure', locals: {object: @store, 
                                                        type_of_form: 'Store',
                                                        fields: 'fields'} %>

app/views/stores/index.html.erb
<%= render partial: 'partials/index_structure', locals: {model_name: 'store', 
                                                         primary: 'active_stores', 
                                                         secondary: 'inactive_stores',
                                                         sidebar: nil} %>

app/views/stores/new.html.erb
<%= render partial: 'partials/form_structure', locals: {object: @store, 
                                                        type_of_form: 'Store',
                                                        fields: 'fields'} %>

app/views/stores/show.html.erb
<%= render partial: 'partials/show_structure', locals: {model_name: 'store', 
                                                         object: @store,
                                                         primary: 'store_details', 
                                                         secondary: nil,
                                                         sidebar: 'employees_sidebar'} %>