config/routes.rb
Rails.application.routes.draw do

  # Semi-static page routes
  get 'home', to: 'home#index', as: :home
  get 'home/about', to: 'home#about', as: :about
  get 'home/contact', to: 'home#contact', as: :contact
  get 'home/privacy', to: 'home#privacy', as: :privacy
  get 'home/search', to: 'home#search', as: :search

  # Resource routes (maps HTTP verbs to controller actions automatically):
  resources :employees
  resources :stores
  resources :assignments

  # Custom routes
  patch 'assignments/:id/terminate', to: 'assignments#terminate', as: :terminate_assignment

  # You can have the root of your site routed with 'root'
  root 'home#index'
end

app/views/partials/_add_new_object.html.erb
<!-- Add a button for new instances of object -->
  <%= link_to(eval("new_#{model_name}_path"), class: "waves-effect waves-light btn") do %>
    <strong>Add a New <%= model_name.capitalize %></strong>
  <% end %>

app/views/partials/_display_base_errors.html.erb
<% unless object.errors.empty? %>
  <div data-alert data-options="animation_speed:500, animation:'fadeOut';" class="alert-box warning">
    <%= object.errors[:base].first %>
  </div>
<% end %>

app/views/partials/_flash.html.erb
<% flash.each do |name, msg| %>
  <div data-alert data-options="animation_speed:500, animation:'fadeOut';" class="alert-box <%= flash[:notice] ? "success" : "warning" %>">
    <%= msg %>
  </div>
<% end %>

app/views/partials/_footer.html.erb
<p class="supertiny">&nbsp;</p>

<div id="footer" class="center-align">
  
  <%= link_to 'Home', home_path %>&nbsp;&nbsp;::&nbsp;&nbsp;
  <%= link_to 'About A&M Creamery', about_path %>&nbsp;&nbsp;::&nbsp;&nbsp;
  <%= link_to 'Contact Us', contact_path %>&nbsp;&nbsp;::&nbsp;&nbsp;
  <%= link_to 'Privacy Policy', privacy_path %>
  <br />
  <div id="copy">
    Webmaster: <%= mail_to("profh@cmu.edu", "Klingon Code Warrior", encode: "javascript") %> 
    &nbsp;&nbsp;&copy 2020
  </div>

</div>

app/views/partials/_form_structure.html.erb
<div class="row">
  <div class="col s9">
    <div class="card">    
      <div class="card-content">
        <span class="card-title"><%= type_of_form %></span>
        <%= simple_form_for(object) do |f| %>
          <%= f.error_notification %>
          <div class="row">
            <div class="form-inputs">
              <%= render partial: "#{fields}", locals: { f: f } %>
          </div>
        </div>
      </div>
    </div>
      <div class="row">
        <div class="form-actions col s9">
          <%= f.button :submit %>
        </div>
      </div>
    <% end %>
  </div>
</div>
<%= link_to 'Back', :back %>

app/views/partials/_index_structure.html.erb
<div class="row">
  <div class="small-8 columns">
    <!-- primary partial gets displayed here in main div -->
    <%= render partial: "#{primary}" %>
    <!-- sometimes we want another partial below -->
    <% unless secondary.nil? %>
      <p>&nbsp;</p>
      <%= render partial: "#{secondary}" %>
    <% end %>
    
  </div>
  <div class="small-4 columns">
    <!-- render the sidebar, if it exists -->
    <%= render partial: "#{sidebar}" unless sidebar.blank? %>
  </div>
</div>

<!-- Add a button for new instances of object -->
<%= render :partial => 'partials/add_new_object', locals: {model_name: model_name} %>

app/views/partials/_nav.html.erb
<nav id="nav">
  <div class="container">
    <ul class="left hide-on-med-and-down">
      <li><%= link_to 'Stores', stores_path %></li>
      <li><%= link_to 'Employees', employees_path %></li>
      <li><%= link_to 'Assignments', assignments_path %></li>
    </ul>
    <ul class="right">
      <li></li>
    </ul>
  </div>
</nav>

app/views/partials/_object_options.html.erb
<% opt = "#{object.respond_to?(:name) ? object.name : model_name.capitalize }" %>

<div class="form-actions">
    <%= link_to(eval("#{model_name.pluralize}_path"), class: 'waves-effect waves-light btn') do %>
      &nbsp;Display All <%# model_name.pluralize.capitalize %>
    <% end %>
    &nbsp;&nbsp;
  
  <% if controller.respond_to?(:update) %>
    <%= link_to(eval("edit_#{model_name}_path(object)"), class: 'waves-effect waves-light btn') do %>
        &nbsp;<%= "Edit #{opt}" %>
    <% end %>
    &nbsp;&nbsp;
  <% end %>
  
  <% if controller.respond_to?(:destroy) %>
    <%= link_to(eval("#{model_name}_path(object)"), method: 'delete', data: {confirm: "Are you sure you want to permanently delete #{opt}"}, class: 'waves-effect waves-light btn btn-alert') do %>
        &nbsp;<%= "Delete #{opt}" %>
    <% end %>
  <% end %>

</div>

app/views/partials/_show_structure.html.erb
<div class="row">
  <div class="col s8">
    <!-- primary partial gets displayed here in main div -->
    <%= render partial: "#{primary}" %>
    <!-- sometimes we want another partial below -->
    <% unless secondary.nil? %>
      <p>&nbsp;</p>
      <%= render partial: "#{secondary}" %>
    <% end %>
  </div>
  <div class="col s4">
    <!-- render the sidebar, if it exists -->
    <%= render partial: "#{sidebar}" unless sidebar.blank? %>
  </div>
</div>
<div class="row">
  <%= render :partial => 'partials/display_base_errors', locals: {object: object} %>
  <%= render :partial => 'partials/object_options', locals: {model_name: model_name, object: object} %>
</div>

app/views/partials/_topbar.html.erb
<div class="row valign-wrapper" id="topbar">
  <div class="col s1">
    <%# link_to(image_tag('logos/logo_v2_80x80.png'), home_path) %>
  </div>
  <div class="col s10">
    <h2><%= link_to 'A&M Creamery', home_path %></h2>
  </div>
  <div class="col s1">
    &nbsp;
  </div>
</div>